# Changes here will be overwritten by Copier
_commit: v1.4.6-4-gc5b6541
_src_path: gh:lincc-frameworks/python-project-template
author_email: scampos@andrew.cmu.edu
author_name: Sandro Campos
custom_install: false
package_name: benchmarking_asv
project_license: none
project_name: benchmarking-asv
project_organization: lincc-frameworks
