# This workflow will run every 5 min. 
# It will install Python dependencies and run benchmarks.

name: Run benchmarks nightly job

on:
  push:
    branches: [ main ]
  
env:
  PYTHON_VERSION: "3.10"
  WORKING_DIR: ${{ github.workspace }}/benchmarks
  LAST_NIGHTLY_HASH: last-nightly-hash

jobs:

  asv-nightly:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout main branch of the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Python ${{ env.PYTHON_VERSION }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-${{ env.PYTHON_VERSION }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install asv virtualenv

      - name: Create ASV machine config file
        run: asv machine --machine gh-runner --yes

      - name: Cache results (with last nightly commit hash)
        uses: actions/cache@v3
        with:
          path: ${{ env.WORKING_DIR }}
          key: "last-nightly-results"

      - name: Run comparison of main against last nightly build
        run: |
          if [ -f ${{ env.LAST_NIGHTLY_HASH }} ]; then
            git remote add upstream https://github.com/${{ github.repository }}.git
            git fetch upstream
          
            PREV_HASH=$(cat ${{ env.LAST_NIGHTLY_HASH }})
            asv continuous upstream/main $PREV_HASH
            asv compare ${{ github.sha }} $PREV_HASH --sort ratio
          fi

      - name: Update nightly commit hash
        run: echo ${{ github.sha }} > ${{ env.LAST_NIGHTLY_HASH }}