# This workflow will install Python dependencies, run benchmarks with airspeed velocity (asv)
# and publish the results to a dashboard on GH Pages.

name: Run benchmarks with airspeed velocity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  GENERATED_HTML_DIR: benchmarks/html
  ASV_FLAGS: "--config benchmarks/asv.conf.json -v"

jobs:

  run-asv:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout main branch of the repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install asv
          pip install virtualenv

      - name: Create ASV machine config file
        run: asv machine --yes $ASV_FLAGS

      - name: Run ASV for the main branch
        run: asv run $ASV_FLAGS

      - name: Generate dashboard HTML
        if: ${{ github.event_name == 'push' }}
        run: asv publish $ASV_FLAGS

      - name: Deploy to Github pages
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.GENERATED_HTML_DIR }}

      - name: Checkout the PR branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Checking out to $GITHUB_REF"
          git fetch origin $GITHUB_REF
          git checkout FETCH_HEAD
  
      - name: Run comparison of PR against main branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          asv run $ASV_FLAGS
          asv compare main FETCH_HEAD $ASV_FLAGS > results.txt

      - name: Publish comment to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('results.txt', 'utf-8');
            const { data } = await github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: comment,
            });
            console.log("Comment published:", data.html_url);
      