# This workflow will install Python dependencies, run benchmarks with airspeed velocity (asv)
# and publish the results to a dashboard on GH Pages.

name: Run benchmarks with airspeed velocity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  ASV_CONFIG_FILE: benchmarks/asv.conf.json
  GENERATED_HTML_DIR: benchmarks/html

jobs:

  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install asv and virtualenv
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install asv
          pip install virtualenv
      - name: Checkout project repository
        uses: actions/checkout@v3
      - name: Create ASV machine config file
        run: asv machine --config $ASV_CONFIG_FILE --yes -v
      - name: Run ASV for current branch
        run: asv run --config $ASV_CONFIG_FILE -v

  asv-run-main:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: install-dependencies
    # TODO: Load dependencies from prev. job
    steps:
      - name: Generate HTML
        run: asv publish --config $ASV_CONFIG_FILE -v
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: $GENERATED_HTML_DIR

  asv-pull-request:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: install-dependencies
    # TODO: Load dependencies from prev. job
    steps:
      - name: Run comparison against main branch
        run: asv compare --config $ASV_CONFIG_FILE -v main HEAD
      - name: Publish comment to PR
        run: |
          echo "Publishing performance comparison comment..."
      