# This workflow runs pre-commit hooks to enforce code style.
# It is triggered on pull requests to main.

name: Run pre-commit hooks

on:
  pull_request:
    branches: [ main ]

jobs:
  pre-commit-ci:
    runs-on: ubuntu-latest
    env: 
      SKIP: "check-lincc-frameworks-template-version,pytest-check,no-commit-to-branch,validate-pyproject,check-added-large-files,sphinx-build"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()