# This workflow runs pre-commit hooks to promote code style consistency.

name: Run pre-commit hooks

on:
  pull_request:

jobs:
  pre-commit-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --color=always --from=main --to=HEAD
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()